### ISSUE TITLE
Webpack of oui doesn't work

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [kui-shell/oui#36]
I cloned oui (master branch, head is 4eb42b32bf6a48c255073adf1f36d6f88fbf3572).

I built it with `npm ci`, then `npx kui-build-webpack`.

Then `npx kui-run-webpack` and visited the presented URL with a web browser.   There is a superficially ok-looking shell but nothing really works.   The console shows:
![Screen Shot 2019-12-23 at 3 54 59 PM](https://user-images.githubusercontent.com/19649275/71380331-bdf07600-259c-11ea-8aa2-c30ec5203645.png)

Is the `oui` packaging expected to webpack successfully?   That was my planned use case and this was just a first sanity check that it would work out of the box.

**Comment by starpit** [comment]
i am hopeful that #38 and #40 help to resolve this.
